# Site
title:              Investing Knights
bio:                'Join the War of Money'
description:        "Join the War of Money"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://investingknights.com" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:title/"
    layout: post
    author:

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus:
    shortname: investingknights

# Social
analytics-id:       "UA-115738067-1"
twitter:            investingknight
facebook:           default
instagram:          default
github:             investingknights

# personal
location:           New Delhi, India
phone:              +91-8586090287
email:              investingknight@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
